### PR TITLE
Additional function expression

### PR DESCRIPTION
**Pull request by eoxxs**
- Add BIND function expression to be able to add a constant value into a queries result set
```
[:find ?u ?l
:where
[?e :user ?u]
[(bind "all" ?u) ?l]]
```

- Change truncates values to Number for now
- Update test accordingly

### CODE REVIEW

**Comment by comnik** [comment]
Based on the example you give, I do not get the usecase... What is the story here?

**Comment by eoxxs** [comment]
I am adding a value to the result of the rest of the query, in this case I bind the string `all` to the symbol `?l`, s.t. in subsequent queries I can use this new symbol `?l`.
I used that to create an artificial user filter that simply contains all users to be able to run reactive filtering. In the example I am building the are only few users with a filter attribute so that as soon as my queries contain that filter I am restricted to that subset. Here I can add a kind off transient attribute to all user and thus run a user based filter.

**Comment by eoxxs** [comment]
If that makes sense ;)

**Comment by eoxxs** [comment]
I'll close it, but keep the branch. Maybe we'll need it again...

**Pull request closed without merging**
