### PR TITLE
Implementable (WIP)

### PR DESCRIPTION
**Pull request by frankmcsherry**
This is a candidate refactoring of the query plan structure.

There is a new module `plan`, in its own directory, which has a bunch of things. Perhaps these things could be further broken apart.

There is a trait `Implementable`, which has a method `implement` roughly akin to the logic found in `implement_plan`.

There is an enum `Plan` just like before, except that most of its variants are now typed, so for example 

```rust
/// Possible query plan types.
#[derive(Deserialize, Clone, Debug)]
pub enum Plan {
    /// Projection
    Project(Projection<Plan>),
    /// Aggregation
    Aggregate(Aggregate<Plan>),
    /// Union
    Union(Union<Plan>),
```

Where types like `Projection<Plan>` is a type, and it implements `Implementable` (perhaps there is a better verb for constructing the relation from the plan?).

Each of these types contain the logic for their associated operator, and .. they are possibly over-engineered. Each are parametric in a type `P: Implementable` which describe the types of plans they can use to produce their input. For all of them above, that is just the enum `Plan`.

The reason for this madness is that it lets us use `Join<_,_>` with future or other enums. If someone decides they like the idea of a new operator, and introduces say `Concat`, they might want to make a new enum that is mostly the same, and be able to use `Join`, `Project`, `Aggregate` et al without re-writing the types.

---

The main downside with all of this is that I have no clue what it does with the serialization. I *hope* that relatively little of this madness shows up there, but at the least the change from anonymous tuple enum variants to structs will probably result in a different serialization.

Anyhow, for the moment this is mainly for checking out.

### CODE REVIEW

**Comment by comnik** [comment]
The naming really is unfortunate. `impl<P1: Implementable, P2: Implementable> Implementable for`...

How do you like `Binding` instead? That would read as "Bindings evaluate to relations" and would reflect the recursive nature of the `Plan` structure. Alternatively `Bindable` or `Relatable` but that's weird.

**Comment by comnik** [comment]
Quick update on breakage: There was a minor, unrelated bug from the previous PR (fixed in c3087171bf0c11ffd931c56c0dc34dc0de631234).

The basic workings of the plan serialization seem fine, except for `Project`, I'll have to take a closer look to find out why, there doesn't seem to be a difference to the other cases, except for the naming mismatch.

**Comment by comnik** [comment]
Ok, all good. Nothing has to change fundamentally about the JSON representation of plans, but backend and frontend need to agree on struct ordering (otherwise everything would have to be clobbered with named keys).

I did the necessary changes in the frontend. The only thing I'd propose is renaming `struct Projection` to `struct Project` to remain consistent with `Aggregate` and `Join` (although `Union` is a bit off there).

Apart from that, I'd be happy to merge this. All previously passing tests still pass.

**Comment by frankmcsherry** [comment]
`Project` seems like a fine name, keeping with the verb form of things. I think it was the first one I did, and hadn't figured that out yet. Also `PredExpr` is a bit non-conformant here as well.

I'll patch those things up in bit.

**Comment by comnik** [comment]
You're right about `RuleExpr` and `NameExpr` (although they might still need to be renamed to fit?). I think  I'll force users to be explicit in the query, e.g. have them declare global, pre-registered inputs that they want to use as part of the query. Should avoid confusion.

I wasn't really happy with `Entity` & co (I myself have to check the definition constantly) so I'd be happy to have the `Match*` variants.

**Pull request merged**
